version: '3'

services:
  mongo-db:
    container_name: mongo-db
    image: mongo:4.4
    restart: always
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example

  mongo-express:
    container_name: mongo-express
    image: mongo-express
    restart: always
    depends_on:
      - mongo-db
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo-db
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=example

  jupyter-nb-server:
    image: greenhub-fisherman
    build:
      context: .
      dockerfile: ./docker-files/dev/Dockerfile
    depends_on:
      - mongo-db
    volumes:
      - ./data:/home/jovyan/data
      - ./config:/home/jovyan/config
      - ./notebooks:/home/jovyan/work
      - ./storage:/home/jovyan/storage
    ports:
      - 8888:8888