version: '3.4'
services:
  jupyter:
    image: greenhub-fisherman
    build:
      context: .
      dockerfile: ./docker-files/dev/Dockerfile
    volumes:
      - ./notebooks:/home/jovyan/work
      - ./data:/home/jovyan/data
    ports:
      - "8888:8888"